Add option to start Chrome
WordPress/try-wordpress pull request #17
Opened 2024-08-21 14:42 UTC by akirk

Adds a new option so that you can decide which browser to use.

2024-08-21 14:49 UTC, psrpinto approved these changes
Makes sense!

2024-08-21 14:52 UTC, psrpinto requested changes
Actually, this won't work currently because the `watch` only builds firefox

2024-08-21 14:52 UTC, psrpinto commented on package.json
> +		"web-ext:run:firefox": "web-ext -s build/firefox run --target firefox-desktop --pref toolkit.legacyUserProfileCustomizations.stylesheets=true",
I'm curious, what does this allow you to do?

2024-08-21 14:54 UTC, psrpinto commented on package.json
> +		"start:firefox": "concurrently \"npm:watch\" \"npm:web-ext:run:firefox\"",
I guess we need to extract the `--env target=firefox` into here, and change it to `chrome` for the `start:chrome` script.

(Suggestion not tested)

```suggestion
		"start:firefox": "concurrently \"npm:watch -- --env target=firefox\" \"npm:web-ext:run:firefox\"",
```

2024-08-21 15:22 UTC, akirk commented on package.json
> +		"web-ext:run:firefox": "web-ext -s build/firefox run --target firefox-desktop --pref toolkit.legacyUserProfileCustomizations.stylesheets=true",
Oh, yes, sorry. It's an accidental change. I'll remove it.

2024-08-26 14:06 UTC, psrpinto approved these changes
Should be good to go now

2024-08-26 16:09 UTC, merged